name: tests

on: [push, pull_request]

jobs:
  build:
    name: Test on Go ${{ matrix.go-version }}-${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        go-version: [1.23.x]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          cache: true

      - name: Ensure dependencies
        run: go mod tidy

      - name: Run go fmt (Linux)
        if: matrix.os == 'ubuntu-latest'
        shell: bash
        run: |
          gofmt_out=$(gofmt -d -s .)
          if [ -n "$gofmt_out" ]; then
            echo "$gofmt_out"
            exit 1
          fi

      - name: Run go vet
        run: go vet ./...

      - name: Run tests
        run: go test -v -race ./...
